syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.gateway.service.department";
option java_outer_classname = "DepartmentProto";

package department;

service DepartmentGrpcService {
  rpc GetDepartmentById (DepartmentIdProto) returns (DepartmentResponseProto) {}
}

message DepartmentIdProto {
  int64 id = 1;
}

message DepartmentPlainProto {
  int64 id = 1;
  string name = 2;
  string startDate = 3;
}

message DepartmentResponseProto {

  message DepartmentLocationPlainProto {
    int64 id = 1;
    string location = 2;
  }

  int64 id = 1;
  string name = 2;
  string startDate = 3;
  repeated DepartmentLocationPlainProto locationProtos = 4;
}
