syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.gateway.service.department.location";
option java_outer_classname = "DepartmentLocationProto";


package department.location;

service DepartmentLocationGrpcService {
  rpc GetDepartmentLocationById(DepartmentLocationIdProto) returns (DepartmentLocationResponseProto) {}
}

message DepartmentLocationIdProto {
  int64 id = 1;
}

message DepartmentLocationPlainDto {
  int64 id = 1;
  string location = 2;
}

message DepartmentLocationResponseProto {
  message DepartmentPlainProto {
    int64 id = 1;
    string name = 2;
    string startDate = 3;
  }
  int64 id = 1;
  string location = 2;
  DepartmentPlainProto departmentPlainProto = 3;
}