# turn off redundant banner
quarkus.banner.enabled=false

# Host and port
quarkus.http.host=127.0.0.1
quarkus.http.port=7000

# gRPC client
## Authentication grpc service
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.clients.authenticationGrpcService.host=localhost
quarkus.grpc.clients.authenticationGrpcService.port=7373
quarkus.grpc.clients.authenticationGrpcService.use-quarkus-grpc-client=true
## Department grpc service
quarkus.grpc.clients.departmentGrpcService.host=localhost
quarkus.grpc.clients.departmentGrpcService.port=7272
quarkus.grpc.clients.departmentGrpcService.use-quarkus-grpc-client=true
## Assignment grpc service
quarkus.grpc.clients.assignmentGrpcService.host=localhost
quarkus.grpc.clients.assignmentGrpcService.port=7272
quarkus.grpc.clients.assignmentGrpcService.use-quarkus-grpc-client=true

## Without TLS secure channel
quarkus.grpc.server.plain-text=true
quarkus.http.insecure-requests=enabled


# Uncomment for native image build only
quarkus.package.jar.enabled=false

# Cross Origin Resource Sharing - Cors policy
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:7373,grpc://localhost:7373,grpc://localhost:7272


# Docker Build image
quarkus.container-image.build=true
quarkus.container-image.name=human-resource-gateway
quarkus.container-image.tag=1.0.0

# Logging
quarkus.log.min-level=DEBUG
## File log
quarkus.log.file.enable=true
quarkus.log.file.level=DEBUG
quarkus.log.file.path=human-resource-gateway.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t[%t{id}]) %s%e%n
quarkus.log.file.rotation.max-file-size=5M
quarkus.log.file.encoding=UTF-8

## Asynchronous thread for I/O
quarkus.log.file.async=true
quarkus.log.file.rotation.max-backup-index=10
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=false
## Console log
quarkus.log.console.enable=true
quarkus.log.console.format==%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t[%t{id}]) %s%e%n
quarkus.log.console.level=INFO
quarkus.log.console.async=true
## System log
quarkus.log.syslog.enable=true
quarkus.log.syslog.level=SEVERE
quarkus.log.syslog.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%c{3.}] (%t[%t{id}]) %s%e%n
quarkus.log.syslog.app-name=human-resource-gateway-sys
quarkus.log.syslog.async=true

# Rabbit Messaging
## Email plaintext channel
mp.messaging.outgoing.emailPlainText.connector=smallrye-rabbitmq
mp.messaging.outgoing.emailPlainText.exchange.name=emailPlainText

